#line 2 "CxxLexer.c"

#line 4 "CxxLexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cxx_yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cxx_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cxx_yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void cxx_yyrestart (FILE *input_file ,yyscan_t yyscanner );
void cxx_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE cxx_yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void cxx_yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void cxx_yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void cxx_yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void cxx_yypop_buffer_state (yyscan_t yyscanner );

static void cxx_yyensure_buffer_stack (yyscan_t yyscanner );
static void cxx_yy_load_buffer_state (yyscan_t yyscanner );
static void cxx_yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER cxx_yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE cxx_yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE cxx_yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE cxx_yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *cxx_yyalloc (yy_size_t ,yyscan_t yyscanner );
void *cxx_yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void cxx_yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer cxx_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cxx_yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cxx_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cxx_yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cxx_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cxx_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyg->yytext_ptr -= yyg->yy_more_len; \
	yyleng = (size_t) (yy_cp - yyg->yytext_ptr); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 170
#define YY_END_OF_BUFFER 171
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[547] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  171,  168,  148,  169,  168,  100,  168,  102,
       95,  168,   87,   88,   96,   97,   89,   98,   94,  101,
      145,  146,  108,  109,  103,  110,  104,  107,  144,  144,
       92,   93,  105,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,   90,  106,   91,   99,  148,  136,  154,
      155,  154,  154,  158,  159,  158,  158,  162,  163,  162,
      166,  167,  166,  142,  143,  142,  139,  140,  142,  142,
      149,  169,  122,    0,  153,  127,  123,  132,    0,  152,

      125,  115,  128,  116,  129,  113,  111,    0,  150,  151,
      126,  145,  145,  145,    0,  145,  146,  146,  146,  146,
      112,  117,  119,  121,  120,  118,  144,    0,  133,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,   19,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,   32,  144,  144,  144,  144,  144,  144,  144,
      144,   42,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  134,  124,  149,  136,  136,  155,  156,  159,  157,
      157,  160,  160,  161,  164,  164,  165,  143,  137,  138,

      141,  141,  114,  135,  145,  145,  145,  145,    0,  146,
      146,  146,  146,  130,  131,  144,    1,    3,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
       29,  144,  144,  144,   34,  144,  144,  144,   38,  144,
       39,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,   61,  144,  144,  144,  144,  144,  144,  144,  144,
      144,   73,  145,  147,  147,  147,  146,  144,  144,    4,
      144,  144,    7,  144,    9,  144,   11,  144,  144,  144,

      144,  144,  144,  144,  144,  144,   22,   23,  144,  144,
      144,  144,  144,  144,  144,   31,  144,   35,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,   58,
      144,  144,   60,  144,  144,  144,  144,  144,   69,  144,
      144,  144,  144,  147,  147,  147,  147,  144,  144,  144,
        6,    8,   10,  144,  144,   12,   13,   14,  144,  144,
      144,  144,  144,  144,  144,  144,  144,   27,   86,   28,
      144,  144,  144,  144,  144,  144,  144,  144,   43,  144,
      144,  144,  144,  144,  144,  144,   50,  144,  144,  144,

      144,  144,  144,  144,   59,  144,  144,  144,   65,  144,
       67,  144,  144,  144,   72,  144,  147,  144,  144,    2,
        5,  144,  144,  144,  144,  144,  144,  144,   18,   20,
      144,  144,   25,   26,   30,   33,  144,  144,  144,   40,
      144,  144,  144,  144,  144,   46,  144,  144,   49,   51,
       52,   53,   55,   56,  144,  144,  144,   63,  144,  144,
      144,  144,  144,   74,   75,   76,  144,  144,  144,  144,
      144,  144,   17,  144,  144,   36,  144,  144,   82,  144,
      144,   44,  144,  144,  144,  144,  144,  144,   62,  144,
      144,   68,  144,   71,   77,   78,  144,  144,   16,   80,

      144,   24,  144,   81,   41,   85,  144,   47,  144,  144,
      144,   57,  144,   64,   66,   70,  144,   79,  144,   37,
       45,  144,  144,  144,  144,   15,  144,  144,  144,  144,
      144,  144,  144,  144,   54,  144,   21,  144,  144,   84,
      144,   83,  144,  144,   48,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   23,   24,   23,   25,   25,   26,   27,   28,
       29,   30,   31,    1,   32,   32,   32,   32,   32,   32,
       33,   33,   33,   33,   33,   34,   33,   33,   33,   33,
       33,   33,   33,   33,   35,   33,   33,   36,   33,   33,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   33,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    5,    4,    1,    1,    1,    1,
        4,    3,    3,    3,    3,    3,    3,    4,    4,    4,
        4,    5,    4,    4,    4,    4,    4,    4,    4,    4,
        5,    4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[557] =
    {   0,
        0,   69,   69,   71,   74,   76,   71,   73,   79,   80,
       84,   89,  654,  655,  651,  655,  649,  622,  644,  620,
       87,  638,  655,  655,  618,   75,  655,   90,   84,   92,
      109,   89,  620,  655,   97,  616,  105,  655,    0,  638,
      655,  655,  614,   88,   96,  110,   93,  103,  114,  587,
       44,  586,  579,  129,  118,   42,  593,  128,  136,   54,
      113,  137,  583,  655,  124,  655,  655,  191,  635,  655,
      655,  633,  617,  655,  655,  631,  133,  655,  655,  192,
      655,  655,  200,  655,  655,  630,  655,  655,  187,  204,
      630,  655,  655,  625,  655,  655,  655,  655,  620,  655,

      655,  655,  655,  655,  655,  616,  655,  611,  655,  655,
      655,  190,  182,  145,    0,  180,  184,  186,  188,  192,
      655,  598,  655,  655,  655,  597,    0,  619,  655,  574,
      578,  569,  561,  560,  564,  572,  169,  575,  574,  177,
      202,  554,  560,  554,  551,  127,  559,  556,  554,  550,
      557,  546,    0,  174,  551,  544,  550,  539,  177,  549,
      554,  558,  552,  183,  554,  200,  541,  191,  210,  545,
      541,  205,  197,  537,  206,  542,  533,  209,  541,  539,
      530,  655,  655,  262,  585,  584,  655,  655,  655,  655,
      582,  655,  581,  655,  655,  580,  655,  655,  655,  655,

      655,  579,  655,  655,  231,  655,  547,  528,  236,  232,
      655,  545,  526,  655,  655,  529,  535,    0,  520,  230,
      522,  531,  526,  527,  512,  510,  512,  214,  515,  524,
      519,  521,  521,  516,  508,  223,  514,  500,  516,  515,
        0,  510,  500,  504,    0,  505,  510,  505,    0,  486,
      508,  496,  489,  500,  487,  482,  483,  490,  491,  486,
      478,  480,  483,  490,  475,  473,  473,  476,  472,  231,
      484,    0,  483,  473,  477,  472,  465,  479,  481,  480,
      469,  479,  655,  245,  242,  246,  655,  465,  472,    0,
      463,  458,    0,  464,    0,  465,  262,  454,  460,  451,

      460,  449,  447,  447,  454,  452,    0,    0,  454,  445,
      444,  455,  448,  439,  444,    0,  443,    0,  453,  436,
      450,  447,  436,  449,  433,  431,  446,  441,  436,  426,
      424,  425,  422,  435,  425,  429,  434,  433,  424,    0,
      433,  411,    0,  245,  419,  424,  423,  409,    0,  409,
      410,  421,  420,  248,  655,  431,  412,  245,  406,  417,
        0,    0,    0,  437,  439,    0,    0,  250,  405,  393,
      405,  410,  409,  404,  409,  392,  397,    0,    0,    0,
      405,  403,  396,  391,  400,  388,  384,  383,    0,  392,
      381,  396,  395,  378,  391,  382,    0,  390,  387,  389,

      372,  382,  388,  384,    0,  382,  382,  384,    0,  371,
        0,  382,  373,  381,    0,  364,  655,  361,  372,    0,
        0,  377,  376,  372,  351,  353,  357,  352,    0,    0,
      367,  360,    0,    0,    0,    0,  363,  366,  351,    0,
      348,  350,  359,  357,  342,    0,  355,  342,    0,    0,
        0,  358,    0,    0,  338,  356,  349,    0,  342,  348,
      341,  340,  331,    0,    0,    0,  330,  329,  346,  331,
      340,  339,    0,  343,  323,    0,  338,  321,    0,  322,
      333,    0,  332,  319,  320,  259,  329,  322,    0,  327,
      327,    0,  325,    0,    0,    0,  311,  311,    0,    0,

      324,    0,  321,    0,    0,    0,  321,    0,  307,  305,
      321,    0,  307,    0,    0,    0,  301,    0,  318,    0,
        0,  313,  299,  298,  312,    0,  296,  287,  300,  248,
      263,  244,  261,  231,    0,  183,    0,  155,  129,    0,
      118,    0,   79,   55,    0,  655,  309,  314,  319,  324,
      329,  334,  339,  343,  347,  351
    } ;

static yyconst flex_int16_t yy_def[557] =
    {   0,
      546,    1,  547,  547,  548,  548,  549,  549,  550,  550,
      551,  551,  546,  546,  546,  546,  546,  546,  552,  546,
      546,  553,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  554,  546,  546,  546,  546,  546,  546,  555,  555,
      546,  546,  546,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  552,  546,  546,  546,  546,  553,  546,

      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  556,  546,  554,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  555,  552,  546,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,

      546,  546,  546,  546,  546,  546,  546,  546,  556,  546,
      546,  546,  546,  546,  546,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  546,  546,  546,  546,  546,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,

      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  546,  546,  546,  546,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,

      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  546,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,

      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,  555,  555,  555,  555,  555,
      555,  555,  555,  555,  555,    0,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546
    } ;

static yyconst flex_int16_t yy_nxt[726] =
    {   0,
       14,   15,   16,   17,   18,   19,   14,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       32,   32,   32,   32,   32,   33,   34,   35,   36,   37,
       38,   39,   39,   40,   39,   39,   41,   14,   42,   43,
       39,   44,   45,   46,   47,   48,   49,   50,   39,   51,
       39,   52,   53,   54,   55,   56,   39,   57,   58,   59,
       60,   61,   62,   63,   39,   39,   64,   65,   66,   67,
       68,   71,   72,   71,   72,   69,   75,   76,   75,   76,
       79,   73,   79,   73,   82,   82,   85,   86,  102,   87,
      153,   85,   86,   88,   87,   97,  107,  154,   88,  164,

      108,   89,  165,  103,  109,  104,   89,  175,   80,  110,
       80,   77,  176,   77,  545,   98,   83,   83,  105,  106,
      111,   90,  118,  119,  122,  123,   90,  112,  112,  112,
      112,  112,  112,  125,  126,  190,  191,  544,  141,  130,
      120,  131,  113,  114,  115,  134,  132,  142,  133,  119,
      135,  137,  182,  136,  144,  147,  145,  143,  138,  543,
      116,  139,  177,  148,  140,  149,  146,  178,  150,  114,
      157,  151,  115,  161,  158,  162,  167,  168,  207,  163,
      179,  171,  236,  159,  172,  180,  237,  169,  542,  160,
      170,  183,  184,  173,  192,  193,  208,  185,  541,  199,

      174,  194,  195,  196,  200,  197,  201,  202,  112,  112,
      112,  112,  112,  112,  206,  205,  206,  118,  119,  210,
      211,  212,  250,  113,  114,  244,  211,  223,  224,  227,
      228,  205,  256,  245,  540,  120,  251,  257,  263,  213,
      206,  116,  206,  210,  119,  229,  211,  259,  230,  260,
      114,  265,  211,  231,  269,  274,  264,  271,  278,  261,
      279,  272,  270,  184,  275,  206,  211,  266,  185,  284,
      285,  291,  300,  301,  309,  356,  341,  310,  354,  355,
      355,  364,  355,  365,  292,  342,  418,  286,  539,  406,
      424,  206,  211,  357,  407,  425,  285,  354,  408,  419,

      510,  538,  511,  537,  536,  355,  355,  535,  355,   70,
       70,   70,   70,   70,   74,   74,   74,   74,   74,   78,
       78,   78,   78,   78,   81,   81,   81,   81,   81,   84,
       84,   84,   84,   84,   94,   94,   94,   94,   94,   99,
       99,   99,   99,   99,  117,  534,  533,  117,  127,  127,
      127,  127,  209,  209,  532,  531,  530,  529,  528,  527,
      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  515,  514,  513,  512,  509,  508,  507,  506,  505,
      504,  503,  502,  501,  500,  499,  498,  497,  496,  495,
      494,  493,  492,  491,  490,  489,  488,  487,  486,  485,

      484,  483,  482,  481,  480,  479,  478,  477,  476,  475,
      474,  473,  472,  471,  470,  469,  468,  467,  466,  465,
      464,  463,  462,  461,  460,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  423,
      422,  421,  420,  417,  417,  416,  415,  414,  413,  412,
      411,  410,  409,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,

      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  363,  362,  361,  360,  359,  358,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      308,  307,  306,  305,  304,  303,  302,  299,  298,  297,
      296,  295,  294,  293,  290,  289,  288,  287,  287,  283,
      283,  201,  195,  192,  190,  186,  186,  282,  281,  280,
      277,  276,  273,  268,  267,  262,  258,  255,  254,  253,

      252,  249,  248,  247,  246,  243,  242,  241,  240,  239,
      238,  235,  234,  233,  232,  226,  225,  222,  221,  220,
      219,  218,  217,  216,   95,  215,  214,  204,  203,  100,
       95,   91,  198,  189,  188,  187,  186,  181,  166,  156,
      155,  152,  129,  128,  124,  121,  101,  100,   96,   95,
       93,   92,   91,  546,   13,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,

      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546
    } ;

static yyconst flex_int16_t yy_chk[726] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    3,    3,    4,    4,    2,    5,    5,    6,    6,
        7,    3,    8,    4,    9,   10,   11,   11,   26,   11,
       51,   12,   12,   11,   12,   21,   29,   51,   12,   56,

       29,   11,   56,   26,   30,   28,   12,   60,    7,   30,
        8,    5,   60,    6,  544,   21,    9,   10,   28,   28,
       30,   11,   32,   32,   35,   35,   12,   31,   31,   31,
       31,   31,   31,   37,   37,   77,   77,  543,   47,   44,
       32,   44,   31,   31,   31,   45,   44,   47,   44,   32,
       45,   46,   65,   45,   48,   49,   48,   47,   46,  541,
       31,   46,   61,   49,   46,   49,   48,   61,   49,   31,
       54,   49,   31,   55,   54,   55,   58,   58,  114,   55,
       62,   59,  146,   54,   59,   62,  146,   58,  539,   54,
       58,   65,   68,   59,   80,   80,  114,   68,  538,   89,

       59,   80,   83,   83,   89,   83,   90,   90,  112,  112,
      112,  112,  112,  112,  116,  113,  113,  117,  117,  118,
      118,  119,  159,  112,  112,  154,  120,  137,  137,  140,
      140,  116,  164,  154,  536,  117,  159,  164,  168,  119,
      116,  112,  113,  120,  117,  141,  118,  166,  141,  166,
      112,  169,  120,  141,  172,  175,  168,  173,  178,  166,
      178,  173,  172,  184,  175,  205,  210,  169,  184,  209,
      209,  220,  228,  228,  236,  285,  270,  236,  284,  284,
      286,  297,  354,  297,  220,  270,  358,  209,  534,  344,
      368,  205,  210,  285,  344,  368,  209,  286,  344,  358,

      486,  533,  486,  532,  531,  284,  286,  530,  354,  547,
      547,  547,  547,  547,  548,  548,  548,  548,  548,  549,
      549,  549,  549,  549,  550,  550,  550,  550,  550,  551,
      551,  551,  551,  551,  552,  552,  552,  552,  552,  553,
      553,  553,  553,  553,  554,  529,  528,  554,  555,  555,
      555,  555,  556,  556,  527,  525,  524,  523,  522,  519,
      517,  513,  511,  510,  509,  507,  503,  501,  498,  497,
      493,  491,  490,  488,  487,  485,  484,  483,  481,  480,
      478,  477,  475,  474,  472,  471,  470,  469,  468,  467,
      463,  462,  461,  460,  459,  457,  456,  455,  452,  448,

      447,  445,  444,  443,  442,  441,  439,  438,  437,  432,
      431,  428,  427,  426,  425,  424,  423,  422,  419,  418,
      416,  414,  413,  412,  410,  408,  407,  406,  404,  403,
      402,  401,  400,  399,  398,  396,  395,  394,  393,  392,
      391,  390,  388,  387,  386,  385,  384,  383,  382,  381,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  365,
      364,  360,  359,  357,  356,  353,  352,  351,  350,  348,
      347,  346,  345,  342,  341,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  317,  315,  314,  313,

      312,  311,  310,  309,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  296,  294,  292,  291,  289,  288,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  271,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      248,  247,  246,  244,  243,  242,  240,  239,  238,  237,
      235,  234,  233,  232,  231,  230,  229,  227,  226,  225,
      224,  223,  222,  221,  219,  217,  216,  213,  212,  208,
      207,  202,  196,  193,  191,  186,  185,  181,  180,  179,
      177,  176,  174,  171,  170,  167,  165,  163,  162,  161,

      160,  158,  157,  156,  155,  152,  151,  150,  149,  148,
      147,  145,  144,  143,  142,  139,  138,  136,  135,  134,
      133,  132,  131,  130,  128,  126,  122,  108,  106,   99,
       94,   91,   86,   76,   73,   72,   69,   63,   57,   53,
       52,   50,   43,   40,   36,   33,   25,   22,   20,   19,
       18,   17,   15,   13,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,

      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[171] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 
    1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() (yyg->yy_more_flag = 1)
#define YY_MORE_ADJ yyg->yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "cxx.l"
/* C++ 词法分析器，不支持续行的，理论上，续行是在预处理阶段搞定的，
   gcc 就是如此处理的。暂时只用最简单的实现处理大多数的情况
   NOTE(2012-06-28):
     忽略所有预处理指令
     不支持普通状态下的续行，其他四种全局状态的续行已经支持 */
#line 8 "cxx.l"
#include <stdio.h>
#include "CxxLexPrvtData.h"
#ifdef _STANDALONE
/* 不和 yacc 一起用的时候 */
# include "symbols.h"
#else
# ifndef __CXXPARSER_HPP__
# define __CXXPARSER_HPP__
#  include "CxxParser.hpp"
# endif
#endif
/* 纯词法分析器的私有数据结构，在规则部分通过宏 yyextra 获取 */
/* ======================================================================= */
/* 基本符号定义 */
/* 通用字符名 */
/* 浮点指数部分 */
/* 整数长度 */
/* ======================================================================= */
/* 其他四种全局状态 */


/* 未用 */

/* 未用 */

/* 简单处理宏的情况，暂时全部忽略 */

#line 844 "CxxLexer.c"

#define INITIAL 0
#define X_CXX_CCOMMENT 1
#define X_CXX_COMMENT 2
#define X_CXX_CHAR 3
#define X_CXX_STRING 4
#define X_CXX_PREPROC 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE CxxLexPrvtData *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int cxx_yylex_init (yyscan_t* scanner);

int cxx_yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cxx_yylex_destroy (yyscan_t yyscanner );

int cxx_yyget_debug (yyscan_t yyscanner );

void cxx_yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE cxx_yyget_extra (yyscan_t yyscanner );

void cxx_yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *cxx_yyget_in (yyscan_t yyscanner );

void cxx_yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *cxx_yyget_out (yyscan_t yyscanner );

void cxx_yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int cxx_yyget_leng (yyscan_t yyscanner );

char *cxx_yyget_text (yyscan_t yyscanner );

int cxx_yyget_lineno (yyscan_t yyscanner );

void cxx_yyset_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cxx_yywrap (yyscan_t yyscanner );
#else
extern int cxx_yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cxx_yylex (yyscan_t yyscanner);

#define YY_DECL int cxx_yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 54 "cxx.l"



    /* 可在这里通过 yyextra 获取私有数据结构（不能这样用） */
    /*static CxxLexPrvtData *s_pPrvtdata = yyextra;*/


 /* C++ 关键词 */
#line 1085 "CxxLexer.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cxx_yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				cxx_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		cxx_yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yyg->yy_more_len = 0;
		if ( yyg->yy_more_flag )
			{
			yyg->yy_more_len = yyg->yy_c_buf_p - yyg->yytext_ptr;
			yyg->yy_more_flag = 0;
			}
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 547 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 655 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = yyg->yy_more_len; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "cxx.l"
{ return CXX_KW_and; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 63 "cxx.l"
{ return CXX_KW_and_eq; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "cxx.l"
{ return CXX_KW_asm; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "cxx.l"
{ return CXX_KW_auto; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "cxx.l"
{ return CXX_KW_bitand; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 67 "cxx.l"
{ return CXX_KW_bitor; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "cxx.l"
{ return CXX_KW_bool; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 69 "cxx.l"
{ return CXX_KW_break; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 70 "cxx.l"
{ return CXX_KW_case; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "cxx.l"
{ return CXX_KW_catch; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "cxx.l"
{ return CXX_KW_char; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 73 "cxx.l"
{ return CXX_KW_class; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 74 "cxx.l"
{ return CXX_KW_compl; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 75 "cxx.l"
{ return CXX_KW_const; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 76 "cxx.l"
{ return CXX_KW_const_cast; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "cxx.l"
{ return CXX_KW_continue; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "cxx.l"
{ return CXX_KW_default; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "cxx.l"
{ return CXX_KW_delete; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 80 "cxx.l"
{ return CXX_KW_do; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 81 "cxx.l"
{ return CXX_KW_double; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 82 "cxx.l"
{ return CXX_KW_dynamic_cast; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 83 "cxx.l"
{ return CXX_KW_else; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 84 "cxx.l"
{ return CXX_KW_enum; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 85 "cxx.l"
{ return CXX_KW_explicit; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 86 "cxx.l"
{ return CXX_KW_export; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 87 "cxx.l"
{ return CXX_KW_extern; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 88 "cxx.l"
{ return CXX_KW_false; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 89 "cxx.l"
{ return CXX_KW_float; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 90 "cxx.l"
{ return CXX_KW_for; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 91 "cxx.l"
{ return CXX_KW_friend; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 92 "cxx.l"
{ return CXX_KW_goto; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 93 "cxx.l"
{ return CXX_KW_if; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 94 "cxx.l"
{ return CXX_KW_inline; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 95 "cxx.l"
{ return CXX_KW_int; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 96 "cxx.l"
{ return CXX_KW_long; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 97 "cxx.l"
{ return CXX_KW_mutable; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "cxx.l"
{ return CXX_KW_namespace; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "cxx.l"
{ return CXX_KW_new; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 100 "cxx.l"
{ return CXX_KW_not; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 "cxx.l"
{ return CXX_KW_not_eq; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 102 "cxx.l"
{ return CXX_KW_operator; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 103 "cxx.l"
{ return CXX_KW_or; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 "cxx.l"
{ return CXX_KW_or_eq; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "cxx.l"
{ return CXX_KW_private; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 "cxx.l"
{ return CXX_KW_protected; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 107 "cxx.l"
{ return CXX_KW_public; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 108 "cxx.l"
{ return CXX_KW_register; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "cxx.l"
{ return CXX_KW_reinterpret_cast; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 110 "cxx.l"
{ return CXX_KW_return; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 111 "cxx.l"
{ return CXX_KW_short; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 "cxx.l"
{ return CXX_KW_signed; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 "cxx.l"
{ return CXX_KW_sizeof; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 114 "cxx.l"
{ return CXX_KW_static; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 115 "cxx.l"
{ return CXX_KW_static_cast; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "cxx.l"
{ return CXX_KW_struct; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 117 "cxx.l"
{ return CXX_KW_switch; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 118 "cxx.l"
{ return CXX_KW_template; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 119 "cxx.l"
{ return CXX_KW_this; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 120 "cxx.l"
{ return CXX_KW_throw; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 121 "cxx.l"
{ return CXX_KW_true; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 122 "cxx.l"
{ return CXX_KW_try; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 123 "cxx.l"
{ return CXX_KW_typedef; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 124 "cxx.l"
{ return CXX_KW_typeid; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 125 "cxx.l"
{ return CXX_KW_typename; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 126 "cxx.l"
{ return CXX_KW_union; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 127 "cxx.l"
{ return CXX_KW_unsigned; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 128 "cxx.l"
{ return CXX_KW_using; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 129 "cxx.l"
{ return CXX_KW_virtual; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 130 "cxx.l"
{ return CXX_KW_void; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 131 "cxx.l"
{ return CXX_KW_volatile; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 132 "cxx.l"
{ return CXX_KW_wchar_t; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 133 "cxx.l"
{ return CXX_KW_while; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 134 "cxx.l"
{ return CXX_KW_xor; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 135 "cxx.l"
{ return CXX_KW_xor_eq; }
	YY_BREAK
/* ==================== C++11 ==================== */
case 75:
YY_RULE_SETUP
#line 137 "cxx.l"
{ return CXX_KW_alignas; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 138 "cxx.l"
{ return CXX_KW_alignof; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 139 "cxx.l"
{ return CXX_KW_char16_t; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 140 "cxx.l"
{ return CXX_KW_char32_t; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 141 "cxx.l"
{ return CXX_KW_constexpr; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 142 "cxx.l"
{ return CXX_KW_decltype; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 143 "cxx.l"
{ return CXX_KW_noexcept; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 144 "cxx.l"
{ return CXX_KW_nullptr; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 145 "cxx.l"
{ return CXX_KW_static_assert; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 146 "cxx.l"
{ return CXX_KW_thread_local; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 147 "cxx.l"
{ return CXX_KW_override; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 148 "cxx.l"
{ return CXX_KW_final; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 151 "cxx.l"
{ return (CXX_OP_LParen); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 152 "cxx.l"
{ return (CXX_OP_RParen); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 153 "cxx.l"
{ return (CXX_OP_Comma); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 154 "cxx.l"
{ return (CXX_OP_LBrace); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 155 "cxx.l"
{ return (CXX_OP_RBrace); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 156 "cxx.l"
{ return (CXX_OP_LBracket); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 157 "cxx.l"
{ return (CXX_OP_RBracket); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 158 "cxx.l"
{ return (CXX_OP_Dot); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 159 "cxx.l"
{ return (CXX_OP_And); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 160 "cxx.l"
{ return (CXX_OP_Mul); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 161 "cxx.l"
{ return (CXX_OP_Plus); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 162 "cxx.l"
{ return (CXX_OP_Minus); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 163 "cxx.l"
{ return (CXX_OP_BitNot); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 164 "cxx.l"
{ return (CXX_OP_Not); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 165 "cxx.l"
{ return (CXX_OP_Div); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 166 "cxx.l"
{ return (CXX_OP_Mod); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 167 "cxx.l"
{ return (CXX_OP_LT); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 168 "cxx.l"
{ return (CXX_OP_GT); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 169 "cxx.l"
{ return (CXX_OP_XOR); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 170 "cxx.l"
{ return (CXX_OP_Or); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 171 "cxx.l"
{ return (CXX_OP_Question); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 172 "cxx.l"
{ return (CXX_OP_Colon); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 173 "cxx.l"
{ return (CXX_OP_Semicolon); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 174 "cxx.l"
{ return (CXX_OP_Equal); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 176 "cxx.l"
{ return (CXX_OP_DotStar); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 177 "cxx.l"
{ return (CXX_OP_ColonColon); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 178 "cxx.l"
{ return (CXX_OP_Arrow); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 179 "cxx.l"
{ return (CXX_OP_ArrowStar); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 180 "cxx.l"
{ return (CXX_OP_Incr); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 181 "cxx.l"
{ return (CXX_OP_Decr); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 182 "cxx.l"
{ return (CXX_OP_LShift); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 183 "cxx.l"
{ return (CXX_OP_RShift); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 184 "cxx.l"
{ return (CXX_OP_LE); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 185 "cxx.l"
{ return (CXX_OP_GE); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 186 "cxx.l"
{ return (CXX_OP_EQ); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 187 "cxx.l"
{ return (CXX_OP_NE); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 188 "cxx.l"
{ return (CXX_OP_AndAnd); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 189 "cxx.l"
{ return (CXX_OP_OrOr); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 190 "cxx.l"
{ return (CXX_OP_MulEqual); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 191 "cxx.l"
{ return (CXX_OP_DivEqual); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 192 "cxx.l"
{ return (CXX_OP_ModEqual); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 193 "cxx.l"
{ return (CXX_OP_PlusEqual); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 194 "cxx.l"
{ return (CXX_OP_MinusEqual); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 195 "cxx.l"
{ return (CXX_OP_LShiftEqual); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 196 "cxx.l"
{ return (CXX_OP_RShiftEqual); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 197 "cxx.l"
{ return (CXX_OP_AndEqual); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 198 "cxx.l"
{ return (CXX_OP_XOREqual); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 199 "cxx.l"
{ return (CXX_OP_OrEqual); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 200 "cxx.l"
{ return (CXX_OP_Ellipsis); }
	YY_BREAK
/* 预处理指令
  define, undef, include, if, ifdef, ifndef, else, elif, endif, line, error, 
  warning, pragma
  */
/* 预处理全部忽略 */
case 136:
YY_RULE_SETUP
#line 208 "cxx.l"
{ BEGIN X_CXX_PREPROC; }
	YY_BREAK
/* 跳过其他四种全局状态，不需要提取 */
case 137:
YY_RULE_SETUP
#line 210 "cxx.l"
{ yyextra->yySavedState = YY_START; BEGIN X_CXX_CCOMMENT; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 211 "cxx.l"
{ yyextra->yySavedState = YY_START; BEGIN X_CXX_COMMENT; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 212 "cxx.l"
{ yyextra->yySavedState = YY_START; BEGIN X_CXX_STRING; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 213 "cxx.l"
{ yyextra->yySavedState = YY_START; BEGIN X_CXX_CHAR; }
	YY_BREAK
case 141:
/* rule 141 can match eol */
YY_RULE_SETUP
#line 214 "cxx.l"
{ /* 续行 */ }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 215 "cxx.l"
{ /* 全部忽略 */ }
	YY_BREAK
case 143:
/* rule 143 can match eol */
YY_RULE_SETUP
#line 216 "cxx.l"
{ BEGIN INITIAL; }
	YY_BREAK
case YY_STATE_EOF(X_CXX_PREPROC):
#line 217 "cxx.l"
{ yyterminate(); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 220 "cxx.l"
{ return CXX_WORD; }
	YY_BREAK
/* 整数 */
case 145:
#line 224 "cxx.l"
case 146:
#line 225 "cxx.l"
case 147:
YY_RULE_SETUP
#line 225 "cxx.l"
{ return CXX_INTEGER; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 227 "cxx.l"
{ /*return CXX_BLANK;*/ /* 忽略空白 */ }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 228 "cxx.l"
{ /*return CXX_BLANKS;*/ /* 忽略空白 */ }
	YY_BREAK
/* 跳过 C 注释 */
case 150:
YY_RULE_SETUP
#line 231 "cxx.l"
{ yyextra->yySavedState = YY_START; BEGIN X_CXX_CCOMMENT; }
	YY_BREAK
/* 跳过 C++ 注释 */
case 151:
YY_RULE_SETUP
#line 234 "cxx.l"
{ yyextra->yySavedState = YY_START; BEGIN X_CXX_COMMENT; }
	YY_BREAK
/* 普通状态时，需要提取字符和字符串，所以不是用这种方式
\'      { yyextra->yySavedState = YY_START; BEGIN X_CXX_CHAR; }
\"      { yyextra->yySavedState = YY_START; BEGIN X_CXX_STRING; }
 */
/* 提取字符，错误的格式也会包含进 yytext */
case 152:
/* rule 152 can match eol */
YY_RULE_SETUP
#line 242 "cxx.l"
{   

    /* '"' 前面的连续的反斜杠的总数，只有为奇数时才需要特殊处理 */
    int cnt = 0;
    int i;
    for ( i = yyleng - 2; i >= 0; i-- ) {
        if ( yytext[i] != '\\' ) {
            break;
        }
        cnt += 1;
    }
    
    if ( cnt & 0x1 ) {
            yyless(yyleng-1);
            yymore();
        } else {
            return CXX_CHAR;
        }
}
	YY_BREAK
/* 提取字符串 */
case 153:
/* rule 153 can match eol */
YY_RULE_SETUP
#line 263 "cxx.l"
{
    /* '"' 前面的连续的反斜杠的总数，只有为奇数时才需要特殊处理 */
    int cnt = 0;
    int i;
    for ( i = yyleng - 2; i >= 0; i-- ) {
        if ( yytext[i] != '\\' ) {
            break;
        }
        cnt += 1;
    }

    if ( cnt & 0x1 ) {
        yyless(yyleng-1);
        yymore();
    } else {
        return CXX_STRING;
    }
}
	YY_BREAK
/* ========================================================================= */
/* 除普通状态外的其他四个全局状态，需要跳过的时候用，需要提取的话，不能用 */
/* 跳过 C 注释 */
case 154:
#line 286 "cxx.l"
case 155:
/* rule 155 can match eol */
YY_RULE_SETUP
#line 286 "cxx.l"
{ /* 忽略 */ }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 287 "cxx.l"
{ BEGIN yyextra->yySavedState; }
	YY_BREAK
case YY_STATE_EOF(X_CXX_CCOMMENT):
#line 288 "cxx.l"
{ yyterminate(); }
	YY_BREAK
/* 跳过 C++ 注释 */
case 157:
/* rule 157 can match eol */
YY_RULE_SETUP
#line 291 "cxx.l"
{ /* 支持续行了 */ }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 292 "cxx.l"
{ }
	YY_BREAK
case 159:
/* rule 159 can match eol */
YY_RULE_SETUP
#line 293 "cxx.l"
{ yyless(0); BEGIN yyextra->yySavedState; }
	YY_BREAK
case YY_STATE_EOF(X_CXX_COMMENT):
#line 294 "cxx.l"
{ yyterminate(); }
	YY_BREAK
/* 需要跳过字符的时候用，需要提取的话，不能用 */
case 160:
/* rule 160 can match eol */
YY_RULE_SETUP
#line 297 "cxx.l"
{ /* 支持续行 */ }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 298 "cxx.l"
{ }
	YY_BREAK
case 162:
/* rule 162 can match eol */
YY_RULE_SETUP
#line 299 "cxx.l"
{ }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 300 "cxx.l"
{ BEGIN yyextra->yySavedState; }
	YY_BREAK
case YY_STATE_EOF(X_CXX_CHAR):
#line 301 "cxx.l"
{ yyterminate(); }
	YY_BREAK
/* 需要跳过字符串的时候用，需要提取的话，不能用 */
case 164:
/* rule 164 can match eol */
YY_RULE_SETUP
#line 304 "cxx.l"
{ /* 支持续行 */ }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 305 "cxx.l"
{ }
	YY_BREAK
case 166:
/* rule 166 can match eol */
YY_RULE_SETUP
#line 306 "cxx.l"
{ }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 307 "cxx.l"
{ BEGIN yyextra->yySavedState; }
	YY_BREAK
case YY_STATE_EOF(X_CXX_STRING):
#line 308 "cxx.l"
{ yyterminate(); }
	YY_BREAK
/* ========================================================================= */
case 168:
YY_RULE_SETUP
#line 311 "cxx.l"
{ return CXX_INVALID; }
	YY_BREAK
case 169:
/* rule 169 can match eol */
YY_RULE_SETUP
#line 313 "cxx.l"
{ }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 315 "cxx.l"
{ yyterminate(); }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 317 "cxx.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 2122 "CxxLexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * cxx_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( cxx_yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cxx_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cxx_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cxx_yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cxx_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 547 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 547 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 546);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cxx_yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cxx_yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cxx_yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        cxx_yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            cxx_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	cxx_yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	cxx_yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void cxx_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cxx_yypop_buffer_state();
	 *		cxx_yypush_buffer_state(new_buffer);
     */
	cxx_yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cxx_yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (cxx_yywrap()) processing, but the only time this flag
	 * is looked at is after cxx_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void cxx_yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cxx_yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cxx_yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cxx_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cxx_yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cxx_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cxx_yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cxx_yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void cxx_yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cxx_yyfree((void *) b->yy_ch_buf ,yyscanner );

	cxx_yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cxx_yyrestart() or at EOF.
 */
    static void cxx_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	cxx_yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cxx_yy_init_buffer was _probably_
     * called from cxx_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void cxx_yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cxx_yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void cxx_yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	cxx_yyensure_buffer_stack(yyscanner);

	/* This block is copied from cxx_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cxx_yy_switch_to_buffer. */
	cxx_yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void cxx_yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	cxx_yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		cxx_yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cxx_yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)cxx_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in cxx_yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)cxx_yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in cxx_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cxx_yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cxx_yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cxx_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cxx_yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cxx_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cxx_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE cxx_yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return cxx_yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to cxx_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cxx_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cxx_yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cxx_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cxx_yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cxx_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE cxx_yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int cxx_yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int cxx_yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *cxx_yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *cxx_yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int cxx_yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *cxx_yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void cxx_yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void cxx_yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "cxx_yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void cxx_yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "cxx_yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see cxx_yy_switch_to_buffer
 */
void cxx_yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void cxx_yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int cxx_yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void cxx_yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* cxx_yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int cxx_yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) cxx_yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* cxx_yylex_init_extra has the same functionality as cxx_yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to cxx_yyalloc in
 * the yyextra field.
 */

int cxx_yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    cxx_yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) cxx_yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    cxx_yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cxx_yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cxx_yylex_init()
     */
    return 0;
}

/* cxx_yylex_destroy is for both reentrant and non-reentrant scanners. */
int cxx_yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cxx_yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cxx_yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	cxx_yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        cxx_yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cxx_yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    cxx_yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cxx_yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *cxx_yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cxx_yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see cxx_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 317 "cxx.l"



 /* vi:set et sts=4: */

